wso2/ei-test-integration

- README.md
- run-scenarios.sh
- scenario01/README.md
- scenario01/base-setup.sh
- scenario01/jmeter/01-Dummy-Scenario.jmx
- scenario01/jmeter/01-post-scenario-steps.sh
- scenario01/jmeter/01-pre-scenario-steps.sh
- scenario01/resources/user.properties
- scenario01/run-scenario.sh
- testgrid.yaml
> adding dummy scenario scripts for the testing purposes and this is to be deleted.
> update with a dummy scenario

- scenario01/jmeter/01-pre-scenario-steps.sh
> Changes the `-` to `=` in scenario01/jmeter/01-pre-scenario-steps.sh
> Resolves #2
> Fix wrongly added - instead of = in scenario01/jmeter/01-pre-scenario-steps.sh

- integration-tests/configure_product.py
- integration-tests/const.py
- integration-tests/intg-test-runner.bat
- integration-tests/intg-test-runner.sh
- integration-tests/requirements.txt
- integration-tests/run-intg-test.py
- integration-tests/run-scenario.sh
- integration-tests/testng-server-mgt.xml
- integration-tests/testng.xml
> Create Integration test suite for EI product
> Implement integration scripts for EI product for different infrastructure combinations
- Integration tests
> NA
> OS:Centos  JDK:OracleJDK8  DB:MySQL
OS:Centos  JDK:OpenJDK8  DB:MySQL
OS:Windows  JDK: OracleJDK8  DB:MySQL
OS:Windows  JDK:OpenJDK8  DB:MySQL
> Add EI Integration Test

- integration-tests/configure_product.py
- integration-tests/const.py
- integration-tests/run-intg-test.py
- integration-tests/run-scenario.sh
> Commit changes in const.py
> EI-integartion tests
> Change the constants with the relevant paths.
> NA
> NA
> NA
> NA
> NA
> NA
- Integration tests
> NA
> NA
> NA
> Oracle JDK, CentOS, Mysql
> NA
> Modify constant values in EI integration

- integration-tests/run-scenario.sh
Changing the property name into an existing value called `keyFileLocation`
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Change key-file property name

- integration-tests/const.py
> Contains changes related to renaming the test results directory.
> Rename output directory name to surefire-reports

- integration-tests/run-scenario.sh
> Fix errors in run-scenario.sh
> Fix copying non-existing files

- integration-tests/run-intg-test.py
Enables execution of a custom testng.xml file for all operating systems
> Enable custom testNG execution for all OSes

- integration-tests/const.py
- integration-tests/integration/business-process-tests/pom.xml
- integration-tests/integration/business-process-tests/tests-integration/bpel/src/test/resources/testng-server-mgt.xml
- integration-tests/integration/business-process-tests/tests-integration/bpel/src/test/resources/testng.xml
- integration-tests/integration/business-process-tests/tests-integration/bpmn/src/test/resources/testng.xml
- integration-tests/integration/business-process-tests/tests-integration/humantasks/src/test/resources/testng.xml
- integration-tests/integration/business-process-tests/tests-integration/pom.xml
- integration-tests/integration/mediation-tests/pom.xml
- integration-tests/integration/mediation-tests/tests-mediator-2/src/test/resources/testng.xml
- integration-tests/integration/mediation-tests/tests-patches/src/test/resources/testng.xml
- integration-tests/integration/mediation-tests/tests-service/src/test/resources/testng.xml
- integration-tests/integration/mediation-tests/tests-transport/src/test/resources/testng.xml
- integration-tests/integration/pom.xml
> Disable tests for rc-1 testgrid test
> Add custom testng files

- integration-tests/integration/business-process-tests/tests-integration/bpmn/src/test/resources/testng.xml
- integration-tests/run-scenario.sh
> Contains a syntax fix in a testng file and other minor fixes in run-scenario.sh
> Fix syntax error in testng.xml

- integration-tests/const.py
> Add a missing set of relevant DB scripts for ACTIVITY_DB under business process profile. 
> Modify const.py file by adding paths to the db scripts.
> Add set of dbscripts for ACTIVITY_DB_BPS

- integration-tests/run-scenario.sh
**Purpose**
Add Red Hat Linux 7.4 to testgrid
**Goals**
Run tests in RHEL
**Approach**
Created an AMI for RHEL and added a new OS infra parameter to testgriddb. Finally modified the CF script and run-scenario.sh 
**Security checks**
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Add RHEL ec2 user to run-scenario.sh

- integration-tests/run-scenario.sh
The PR contains necessary changes to align the integration tests with the latest TestGrid-expected-standards.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Modify structure of integration tests to align with current TestGrid execution

- integration-tests/run-scenario.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> create scenarios/ dir

- integration-tests/run-scenario.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Add sleep time to wait till password received for Windows

- wum-releases/run-int-test.sh
This is to add run-int-test.sh for MI 1.2.0
> Add MI 1.2.0 wum release run script

- wum-releases/run-int-test.sh
> Update ei-6.6.0 test script

- wum-releases/run-int-test.sh
Reverts wso2/ei-test-integration#33
> Revert "Update ei-6.6.0 test script"

- wum-releases/run-int-test.sh
> Add ei-6.6.0 product pack to .m2

- wum-releases/run-int-test.sh
> Update mi-1.2.0 script

- wum-releases/run-int-test.sh
Reverts wso2/ei-test-integration#37
> Revert "Update mi-1.2.0 script"

- wum-releases/run-int-test.sh
This PR updates the script with commands to increase the number of Maximum open files
> [MI-1.2.0] Add command to increase number of Max Open files in system

- wum-releases/run-int-test.sh
This PR adds the command to increase the Maximum number of Open files in system
> [EI-6.6.0] Add commands to increase Max-Open files

- wum-releases/run-int-test.sh
> Update mvn install command for EI-6.6.0

- run-int-test.sh
Reverts wso2/ei-test-integration#45
> Revert "Install jq to run tests on RHEL"
